### ISSUE TITLE
能更新一下这个文件吗

### ISSUE THREAD

**Issue by LisonFan** [shadowsocksrr/breakwa11.github.io#2]
breakwa11.github.io/ssr/ss_cnip.pac

或者能否做个脚本自己更新？

**Comment by Akkariiin** [comment]
你可以发一个PR上来呀~ 欢迎发PR~
这个我记得很久没有更新了~

**Comment by LisonFan** [comment]
@Akkariiin 之前有尝试过转换，失败了。。

**Comment by LisonFan** [comment]
@Akkariiin 
[pac.txt](https://github.com/shadowsocksrr/breakwa11.github.io/files/1675611/pac.txt)

把 CN IP 更新了一下，用的我自己的 https://github.com/LisonFan/china_ip_list 这个 IP 库，把域名白名单删了。
